<a href="https://colab.research.google.com/github/soaresbru/aleatorio/blob/main/FTC_Lista_3_Ex_6_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#exemplo 6.1 extraído do capítulo 6 de Versteeg & Malalasekera(2007)

# considerando um fluxo constante, uma dimensão, densidade constante e duto com área de seção transversal constante

# Vamos aplicar o método SIMPLE

# Declarando as variáveis do problema
ro = 1  # é constante, 1 kg/m³ 
d = 1  # é o coeficiente de relaxação
u1 = 10 #é a velocidade que já sabemos na extremidade esquerda
p = 0  # é a pressão que já sabemos na extremidasde direita
A= 1 # A é constante, vamos assumir esse valor, porém não afetará o resultado final, pois o A acaba se cancelando
n=4 # é o número de nós

import numpy as np  # importando a biblioteca numpy

# Vamos fazer alguns chutes para tentar solucionar o problema
u2= 8
u3= 11
u4= 7

# para este método vamos aplicar uma correção para a velocidade
#u = d*(Pnoponto - Pnoponto+1) #correção da pressão para gerar a correção da velocidade
#uu = uchute + u  #campo de velocidade corrigido

# na extremidade esquerda temos
aee= 0 #no ponto esquerdo da extremidade esquerda
aed= ro*d*A # no ponto direito da extremidade esquerda
ae = aee + aed #no ponto esquerdo
#b = (ro*u1*A) - (ro*u2*A)

# no meio temos
ame= ro*d*A #no ponto a esquerda do meio
amd= ro*d*A #no ponto a direita do meio
am= ame + amd #nos pontos do meio
#b= (ro*uantes*A) - (ro*udepois*A)

# na extremidade direita temos
ade = ro*d*A #no ponto esquerdo da extremidade direita
add = 0 # no ponto direito da extremidade direita
ad = ade + add #no ponto direito
#b = (ro*uantes*A) - (ro*udepois*A)

# adicionando qualquer valor para iniciar o looping
cond = np.ones([n-1,1])

#adicionando um contador
cont= 0

#looping para fazer o cálculo até convergir
while (cond.any() > 0.01): #coloquei para parar se a diferença entre a velocidade do chute e a velocidade com a correção for menor que 1%
  cont= cont+1 #adicionando 1 a cada looping para sabermos em qual estamos
  print(' ')
  print('essa é a interação ',cont)
  u=[[u2],[u3],[u4]]  #armazendando os chutes em um variável
  um=[[u1],[u2],[u3],[u4]] #adicionando o valor (u1) que já sabemos 
  umaior= np.array(um)

  # criar uma matriz com os valores de a, sem colocar o p(que é matriz que eu quero saber)
  A= np.zeros((n,n)) #iniciando a matriz de zeros
  for i in range(0,n) :
    if i == 0:  #fazendo o caso para extremidade esquerda
      A[i,i] = ae
      A[i,i+1] = -aed
    if i>0 and i<n-1: #fazendo o caso para os pontos centrais
      A[i,i] = am
      A[i, i-1] = -ame
      A[i, i+1] = -amd
    if i==n-1: #fazendo o caso para a extremidade direita
      A[i,i] = ad
      A[i,i-1] = -ade
  print(' ')
  print('Matriz')
  print(A)

  # porém já sabemos o valor de p na extremidade direita, p=0, então podemos eliminar essa variável
  AA = np.delete(A, (3), axis=0) #eliminando uma linha
  AAA = np.delete(AA,(3), axis=1) #eliminando uma coluna
  print(' ')
  print('Matriz sem a variável p na extremidade direita')
  print(AAA)

  # Preenchendo o vetor b
  B = np.zeros([n-1,1])  #iniciando a matriz
  for j in range(1,n):
    B[j-1]= umaior[j-1] - umaior[j] #preenchendo com os valores

  print(' ')
  print('Matriz B')
  print (B)

  #resolvendo a equação para achar as pressões
  X= np.linalg.solve(AAA,B)
  print(' ')
  print('Pressão: Solução numérica')
  print(X)

  #Agora vamos adicionar o valor de p da extremidade direita que já foi dado pela questão
  XX= np.append(X,0)

  # correção da velocidade
  uu = np.zeros([n-1,1]) #iniciando a matriz
  for k in range (0,n-1):
    uu[k]= u[k] + (d*(XX[k] - XX[k+1] )) #preenchendo a matriz conforme a equação do campo de velocidade corrigido
  print(' ')
  print('Velocidade com a correção')
  print(uu)

  # O novo chute, para a próxima interação vai ser o valor de uu
  u2=uu[0]
  u3=uu[1]
  u4=uu[2]

  # fazer a condição para o looping parar se a equação convergir
  condi = uu - u #velocidade com a correção menos o chute 
  cond= abs(condi) #colocando em número absoluto


 
essa é a interação  1
 
Matriz
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]
 
Matriz sem a variável p na extremidade direita
[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
 
Matriz B
[[ 2.]
 [-3.]
 [ 4.]]
 
Pressão: Solução numérica
[[4.]
 [2.]
 [3.]]
 
Velocidade com a correção
[[10.]
 [10.]
 [10.]]
 
essa é a interação  2
 
Matriz
[[ 1. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  1.]]
 
Matriz sem a variável p na extremidade direita
[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]
 
Matriz B
[[0.]
 [0.]
 [0.]]
 
Pressão: Solução numérica
[[0.]
 [0.]
 [0.]]
 
Velocidade com a correção
[[10.]
 [10.]
 [10.]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:57: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
